export const chatsConst = {
  GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
  ADD_CHAT_SUCCESS: 'ADD_CHAT_SUCCESS',
  ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
  DELL_MESSAGE_SUCCESS: 'DELL_MESSAGE_SUCCESS',
  NOTIF_CHAT_SUCCESS: 'NOTIF_CHAT_SUCCESS',
};
